plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://mvn.devos.one/snapshots" }
    maven { url = "https://maven.blamejared.com/" }
}

base {
    archivesName = "SGP-Create-Chipped-Cutting"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
