{
  "category.wands.general": "Общие",
  "category.wands.preview": "Предпросмотр",
  "item.wands.copper_wand": "Медная палочка",
  "item.wands.creative_wand": "Творческая палочка",
  "item.wands.diamond_wand": "Алмазная палочка",
  "item.wands.gradient": "Градиент",
  "item.wands.iron_wand": "Железная палочка",
  "item.wands.magic_bag_1": "Волшебная сумка 1-го уровня",
  "item.wands.magic_bag_2": "Волшебная сумка 2-го уровня",
  "item.wands.magic_bag_3": "Волшебная сумка 3-го уровня",
  "item.wands.netherite_wand": "Незеритовая палочка",
  "item.wands.palette": "Палитра",
  "item.wands.random": "Случайно",
  "item.wands.round_robin": "По очереди",
  "item.wands.stone_wand": "Каменная палочка",
  "itemGroup.wands.wands_tab": "Строительные палочки",
  "key.categories.wands": "Строительные палочки",
  "key.category.wands.wands": "Строительные палочки",
  "key.wands.area_diagonal_spread": "Диагональное распространение области",
  "key.wands.clear_wand": "Очистить палочку",
  "key.wands.inc_sel_block": "Включить блок в выделение",
  "key.wands.m_dec": "Закрепление влево / уменьшить строки сетки",
  "key.wands.m_inc": "Закрепление вправо / увеличить строки сетки",
  "key.wands.n_dec": "Закрепление вниз или назад / уменьшить столбцы сетки",
  "key.wands.n_inc": "Закрепление вверх или вперёд / увеличить столбцы сетки",
  "key.wands.palette_menu": "Меню палитры",
  "key.wands.toggle_stair_slab": "Переключить ступени/плиты",
  "key.wands.wand_action": "Действие",
  "key.wands.wand_conf": "Конфигурация",
  "key.wands.wand_fill_circle": "Заливка круга",
  "key.wands.wand_invert": "Инвертировать",
  "key.wands.wand_menu": "Меню палочки",
  "key.wands.wand_mode": "Режим",
  "key.wands.wand_orientation": "Ориентация",
  "key.wands.wand_palette_mode": "Режим палитры",
  "key.wands.wand_rotate": "Вращение",
  "key.wands.wand_undo": "Отменить",
  "magic_bag_menu": "Меню волшебной сумки",
  "option.wands.advancement_allow_diamond_wand": "Достижение для алмазной палочки",
  "option.wands.advancement_allow_iron_wand": "Достижение для железной палочки",
  "option.wands.advancement_allow_netherite_wand": "Достижение для незеритовой палочки",
  "option.wands.advancement_allow_stone_wand": "Достижение для каменной палочки",
  "option.wands.allow_copper_tools_to_break": "Разрешить ломать медными инструментами",
  "option.wands.allow_copper_wand_to_break": "Разрешить ломать медной палочкой",
  "option.wands.allow_diamond_tools_to_break": "Разрешить ломать алмазными инструментами",
  "option.wands.allow_diamond_wand_to_break": "Разрешить ломать алмазной палочкой",
  "option.wands.allow_iron_tools_to_break": "Разрешить ломать железными инструментами",
  "option.wands.allow_iron_wand_to_break": "Разрешить ломать железной палочкой",
  "option.wands.allow_netherite_tools_to_break": "Разрешить ломать незеритовыми инструментами",
  "option.wands.allow_netherite_wand_to_break": "Разрешить ломать незеритовой палочкой",
  "option.wands.allow_stone_tools_to_break": "Разрешить ломать каменными инструментами",
  "option.wands.allow_stone_wand_to_break": "Разрешить ломать каменной палочкой",
  "option.wands.allow_wooden_tools_to_break": "Разрешить ломать деревянными инструментами",
  "option.wands.advancement_allow_stone_wand_tt": "",
  "option.wands.allow_offhand_to_break": "Разрешить инструменту ломаться",
  "option.wands.allow_offhand_to_break_tt": "",
  "option.wands.allow_wand_to_break": "Разрешить палочке ломаться",
  "option.wands.allow_wand_to_break_tt": "",
  "option.wands.block_color": "Оттенок блока",
  "option.wands.block_outline_color": "Контур блока",
  "option.wands.block_outlines": "Контуры блоков",
  "option.wands.blocks_per_xp": "Блоков за очко опыта",
  "option.wands.blocks_per_xp_tt": "x=0 отключено; x=1.0 потребляет 1 очко опыта за блок; x>1 потребляет x очков за блок; 0>x<1 потребляет 1/x очков за блок",
  "option.wands.bounding_box_color": "Ограничивающая рамка",
  "option.wands.check_advancements": "Проверять достижения",
  "option.wands.check_advancements_tt": "",
  "option.wands.toast_in_action_bar": "Сообщения в панели действий",
  "option.wands.toast_in_action_bar_tt": "Показывать сообщения об отсутствии или износе инструмента в панели действий вместо всплывающих уведомлений",
  "option.wands.disable_info_messages": "Отключить информационные сообщения",
  "option.wands.disable_info_messages_tt": "Скрыть информационные сообщения в чате (смена режима, очистка палочки и т. п.)",
  "wands.message.no_tool": "Нет инструмента — добавьте инструмент к палочке [%s]",
  "wands.message.damaged_tool": "Инструмент почти сломан — замените инструмент у палочки [%s]",
  "wands.message.wrong_tool": "Неподходящий инструмент — добавьте %1$s к палочке [%2$s]",
  "option.wands.copy_outlines": "Контуры режима копирования",
  "option.wands.destroy_color": "Уничтожить",
  "option.wands.destroy_in_survival_drop": "Выбрасывать предметы при разрушении в выживании",
  "option.wands.destroy_in_survival_drop_tt": "При разрушении блоков в выживании выбрасывать полученные предметы",
  "option.wands.copper_wand_limit": "Лимит медной палочки",
  "option.wands.creative_wand_limit": "Лимит творческой палочки",
  "option.wands.diamond_wand_durability": "Прочность алмазной палочки",
  "option.wands.diamond_wand_limit": "Лимит алмазной палочки",
  "option.wands.end_color": "Конец",
  "option.wands.fancy_preview": "Расширенный предпросмотр",
  "option.wands.fancy_preview_tt": "Показывать расширенный предпросмотр блоков",
  "option.wands.fill_outlines": "Контуры режима заливки",
  "option.wands.iron_wand_durability": "Прочность железной палочки",
  "option.wands.iron_wand_limit": "Лимит железной палочки",
  "option.wands.line_color": "Линия",
  "option.wands.line_thickness": "Толщина линии",
  "option.wands.line_thickness_tt": "Толщина толстых линий",
  "option.wands.lines": "Линии",
  "option.wands.lines_tt": "Отображать линии",
  "option.wands.netherite_wand_durability": "Прочность незеритовой палочки",
  "option.wands.netherite_wand_limit": "Лимит незеритовой палочки",
  "option.wands.opacity": "Непрозрачность",
  "option.wands.opacity_tt": "Непрозрачность предпросмотра блоков",
  "option.wands.paste_bb_color": "Вставить",
  "option.wands.paste_outlines": "Контуры режима вставки",
  "option.wands.render_last": "Отрисовывать последним",
